/**
 * action 类型
 * Songlcy create by 2017-01-11
 */

export const LOAD_OVER = "LOAD_OVER";
// 首页 

export const LOAD_MAIN_LIST = "LOAD_MAIN_LIST";
export const GET_MAIN_LIST = "GET_MAIN_LIST";
export const RESET_MAIN_LIST = "RESET_MAIN_LIST";

// 发现

export const LOAD_DISCOVERY_LIST = "LOAD_DISCOVERY_LIST";
export const GET_DISCOVERY_LIST = "GET_DISCOVERY_LIST";
export const RESET_DISCOVERY_LIST = "RESET_DISCOVERY_LIST";

// 精选

export const LOAD_CHOICE_GRIL_LIST = "LOAD_CHOICE_GRIL_LIST";
export const GET_CHOICE_GRIL_LIST = "GET_CHOICE_GRIL_LIST";
export const RESET_CHOICE_GRIL_LIST = "RESET_CHOICE_GRIL_LIST";

export const LOAD_CHOICE_BEAUTIFUL_LIST = "LOAD_CHOICE_BEAUTIFUL_LIST";
export const GET_CHOICE_BEAUTIFULL_LIST = "GET_CHOICE_BEAUTIFULL_LIST";
export const RESET_CHOICE_BEAUTIFUL_LIST = "RESET_CHOICE_BEAUTIFUL_LIST";

// 章节列表

export const LOAD_CHAPTER_LIST = "LOAD_CHAPTER_LIST";
export const GET_CHAPTER_LIST = "GET_CHAPTER_LIST";
export const RESET_CHAPTER_LIST = "RESET_CHAPTER_LIST";

// 漫画详情

export const LOAD_COMBICK_DETIAL_LIST = "LOAD_COMBICK_DETIAL_LIST";
export const GET_COMBICK_DETIAL_LIST = "GET_COMBICK_DETIAL_LIST";
export const RESET_COMBICK_DETIAL_LIST = "RESET_COMBICK_DETIAL_LIST";

// 收藏  

export const LOAD_COLLECTION_LIST = "LOAD_COLLECTION_LIST";
export const GET_COLLECTION_LIST = "GET_COLLECTION_LIST";
export const RESET_COLLECTION_LIST = "RESET_COLLECTION_LIST";

